#syntax=docker/dockerfile:experimental
FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

RUN apt update && apt install -y fish screen

RUN apt install -y openssh-server openssh-client
RUN echo -e "Port 10122\nPermitRootLogin yes\n" >> /etc/ssh/sshd_config
EXPOSE 30015
RUN echo '/etc/init.d/ssh restart' > /opt/restart_ssh.sh
RUN chmod +x /opt/restart_ssh.sh
WORKDIR /root
ENTRYPOINT fish

